[CI/CD][SpineApp] Added sanity test for spineapp in pull request job. (#353)

diff --git a/.github/workflows/spineapp_pull_request.yaml b/.github/workflows/spineapp_pull_request.yaml
--- a/.github/workflows/spineapp_pull_request.yaml
+++ b/.github/workflows/spineapp_pull_request.yaml
@@ -6,11 +6,11 @@ on:
       - 'main'
     paths:
       - 'manufacturing-ai-suite/industrial-edge-insights-vision/**'
-      
   pull_request:
     paths:
       - 'manufacturing-ai-suite/industrial-edge-insights-vision/**'
-      
+  
+  workflow_dispatch:    
       
   workflow_call:
 permissions: {}
@@ -74,4 +74,63 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
           name: shellcheck-report
-          path: shellcheck_report.txt  
+          path: shellcheck_report.txt
+  sanity:
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+      packages: write
+    strategy:
+      fail-fast: false
+      matrix:
+        include:
+          - ubuntu_version: ubuntu22 
+    steps:
+    - name: Check out edge-ai-suites repository
+      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #4.2.2
+      with:
+        persist-credentials: false
+        path: edge-ai-suites-repo
+    - name: Set up Python
+      uses: actions/setup-python@v5
+      with:
+        python-version: '3.10'
+    - name: Log in to GitHub Container Registry
+      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 #3.4.0
+      with:
+        registry: ghcr.io
+        username: ${{ github.actor }}
+        password: ${{ secrets.GITHUB_TOKEN }}
+    - name: Sanity Test 
+      run: | 
+       sudo apt-get update
+       sudo pip install robotframework
+       sudo apt install -y python3-nose libxml2-utils vlc
+       cd edge-ai-suites-repo/manufacturing-ai-suite/industrial-edge-insights-vision/tests/robot_files
+       robot test.robot || true
+       mkdir -p /tmp/test_results
+       cp -r report.html log.html output.xml /tmp/test_results/
+       passed=$(xmllint --xpath "//return/status[@status='PASS']" ./output.xml | wc -l) || true
+       failed=$(xmllint --xpath "//return/status[@status='FAIL']" ./output.xml | wc -l) || true
+       not_run=$(xmllint --xpath "//return/status[@status='NOT RUN']" ./output.xml | wc -l) || true
+       total=$((passed + failed + not_run))
+       echo "### Sanity Test Summary" >> $GITHUB_STEP_SUMMARY
+       echo "- Total: $total" >> $GITHUB_STEP_SUMMARY
+       echo "- ✅ Passed: $passed" >> $GITHUB_STEP_SUMMARY
+       echo "- ❌ Failed: $failed" >> $GITHUB_STEP_SUMMARY
+       echo "- ⏭️ Not Run: $not_run" >> $GITHUB_STEP_SUMMARY
+       echo "- 📄 [Full Report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> $GITHUB_STEP_SUMMARY
+    - name: Upload Scan artifact to Github
+      uses: actions/upload-artifact@v4
+      with:
+        name: Sanity_Reports
+        path: /tmp/test_results/*
+    - name: Clean up
+      if: always()
+      run: |
+        sudo rm -rf edge-ai-libraries-repo
+        if [ -n "$(docker images -aq)" ]; then
+               docker rmi -f $(docker images -aq) || true
+        fi
+        sudo rm -rf /tmp/test_results/*
+  
